/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import NuevasPantallas.principal;
import beans.Productos;
import control.controlVentas;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.daoProductos;
import validaciones.validarCampos;

/**
 *
 * @author famsa
 */
public class detallesVenderProducto extends javax.swing.JFrame {

    //para el frame
    int x = 0, y = 0;
//=========================== INSTANCIAMOS LA CLASES QUE UTILIZAREMOS ======================================
    controlVentas controlV = new controlVentas();
    validarCampos validar = new validarCampos();
    daoProductos dao = new daoProductos();
    //este bean es llendao desde controlProductos del metodo consultaEspecificaParaEnviarAPantllas()
    public static Productos bean = new Productos();

    //estas tablas vienen desde la pantalla pricipall
    public static JTable tablaProductos = new JTable();
    ;
    public static DefaultTableModel defaultTablaProductos = new DefaultTableModel();
    //ESTOS  VALORES defaultTabla-->SON LLENADOS DESDE LA PANTALLA PRINCIPAL
    public static DefaultTableModel defaultTablaVentas = new DefaultTableModel();
    public static JTable tablaVentas = new JTable();
    public static JTextField txtTotalAPagar;

    /**
     * Creates new form detallesVenderProducto
     */
    public detallesVenderProducto() {
        initComponents();
        //mandamos el frame al principal1 para cerrarlo
        principalUsuarios.framedetallesVenderProducto = this;
        principal.framedetallesVenderProducto = this;

        this.setTitle("Detalles del producto a vender");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        txtCantidadDetallesVenta.requestFocus();
        validar.soloNumerosConPunto(txtCantidadDetallesVenta);
        //llenamos los campos con el bean que traemos desde controlProducto en el metodoconsultaEspecificaParaEnviarAPantllas()
        txtNombreDetallesVenta.setText(bean.getNombre());
        txtPrecioDetallesVenta.setText(bean.getPrecio() + "");
        txtExistenciasDetallesVenta.setText(bean.getCantidad() + "");
        Image imagen = null;

        try {

            if (bean.getFoto() == null) {

                labelFotoDetallesVenta.setIcon(null);
                labelFotoDetallesVenta.setText("Sin foto");
            } else {

                imagen = dao.getImage(bean, false);

                Icon icon = new ImageIcon(imagen.getScaledInstance(160, 210, Image.SCALE_DEFAULT));
                labelFotoDetallesVenta.setIcon(icon);
            }

        } catch (Exception ex) {

            System.out.println("error al cargar al imagen " + ex.getMessage());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelFotoDetallesVenta = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPrecioDetallesVenta = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtExistenciasDetallesVenta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCantidadDetallesVenta = new javax.swing.JTextField();
        txtNombreDetallesVenta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnAceptarDetallesVenta = new javax.swing.JButton();
        btncancelarDetallesVenta = new javax.swing.JButton();
        txtSubTotalDetallesVenta = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));

        labelFotoDetallesVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFotoDetallesVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 204));
        jLabel11.setText("Precio:");

        txtPrecioDetallesVenta.setEditable(false);
        txtPrecioDetallesVenta.setBackground(new java.awt.Color(229, 222, 222));
        txtPrecioDetallesVenta.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtPrecioDetallesVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 204));
        jLabel12.setText("Existencias:");

        txtExistenciasDetallesVenta.setEditable(false);
        txtExistenciasDetallesVenta.setBackground(new java.awt.Color(229, 222, 222));
        txtExistenciasDetallesVenta.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtExistenciasDetallesVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 204));
        jLabel13.setText("Cantidad:");

        txtCantidadDetallesVenta.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtCantidadDetallesVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadDetallesVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadDetallesVentaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadDetallesVentaKeyReleased(evt);
            }
        });

        txtNombreDetallesVenta.setEditable(false);
        txtNombreDetallesVenta.setBackground(new java.awt.Color(229, 222, 222));
        txtNombreDetallesVenta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNombreDetallesVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 204));
        jLabel14.setText("Nombre  del producto:");

        btnAceptarDetallesVenta.setBackground(new java.awt.Color(255, 0, 204));
        btnAceptarDetallesVenta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAceptarDetallesVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptarDetallesVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        btnAceptarDetallesVenta.setText("Aceptar");
        btnAceptarDetallesVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptarDetallesVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarDetallesVentaActionPerformed(evt);
            }
        });

        btncancelarDetallesVenta.setBackground(new java.awt.Color(255, 0, 204));
        btncancelarDetallesVenta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btncancelarDetallesVenta.setForeground(new java.awt.Color(255, 255, 255));
        btncancelarDetallesVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        btncancelarDetallesVenta.setText("Cancelar");
        btncancelarDetallesVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncancelarDetallesVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarDetallesVentaActionPerformed(evt);
            }
        });

        txtSubTotalDetallesVenta.setEditable(false);
        txtSubTotalDetallesVenta.setBackground(new java.awt.Color(229, 222, 222));
        txtSubTotalDetallesVenta.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtSubTotalDetallesVenta.setForeground(new java.awt.Color(204, 0, 51));
        txtSubTotalDetallesVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSubTotalDetallesVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalDetallesVentaActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 204));
        jLabel15.setText("Subtotal:");

        jPanel4.setBackground(new java.awt.Color(255, 0, 204));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Información del producto");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/minimizar.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCantidadDetallesVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(txtExistenciasDetallesVenta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecioDetallesVenta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreDetallesVenta, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel15)
                                .addGap(133, 133, 133))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSubTotalDetallesVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelFotoDetallesVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btncancelarDetallesVenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addComponent(btnAceptarDetallesVenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreDetallesVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioDetallesVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtExistenciasDetallesVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelFotoDetallesVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidadDetallesVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSubTotalDetallesVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(68, 68, 68)))
                .addComponent(btnAceptarDetallesVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncancelarDetallesVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarDetallesVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarDetallesVentaActionPerformed
        //AL MOMENTO DE DAR HACEPTAR  PREGUNTAREMOS SI EL PRODUCTO LLEVARA ALGUN DETALLE?
        //1.-SI --> REGISTRAMOS AL CLIENTE Y LOS DETALLES QUE PUEDEN  SER
        //1.1->MEDIDAS
        //1.2-->FECHAS
        //NOTA PARA EL PUNTO 1 --> SI SE REGISTRA EL CLIENTE Y EL CLIENTE AUN SIGUE COMPRANDO DEBEMOS MANDAR A TRAER ESE ULTIMO
        //CLIENTE REGISTRADO PARA PODER ASIGNAR SU ID ALA DEUDA TOTAL ASI COMO EN PRO APARTADOS

        //2.-NO--> ENTONCES NO REGISTRAMOS AL CLIENTE.
        //PERO  DEBEMOS DE REGISTRAR SU DEUDA TOTAL Y EN LA TABLA DE APRTADOS COMO CLIENTE GENERAL
        //EL CUAL  YA ESTARA POR DEFAUL EL LA BD SIN MOSTRARSE EN LAS PANTALLAS
        int cantidad = Integer.parseInt(txtCantidadDetallesVenta.getText());
        controlV.aceptarDetallesVenta(txtCantidadDetallesVenta, bean, cantidad, this, tablaProductos,
                defaultTablaProductos, tablaVentas, defaultTablaVentas, txtTotalAPagar);

    }//GEN-LAST:event_btnAceptarDetallesVentaActionPerformed

    private void txtCantidadDetallesVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadDetallesVentaKeyPressed
        //CALCULAMOS EL TOTAL A PAGAR DE DICHO PRODUCTO PRECIO * CANTIDAD Y PINTAMOS EL SUBTOTAL
        /* System.out.println("entro");
          System.out.println("esto pongo " +txtCantidadDetallesVenta.getText().toString().trim());
          
            System.out.println("entro  aqui 222");
           int precio=Integer.parseInt(txtPrecioDetallesVenta.getText().toString().trim());
           System.out.println("esto pongo " +  Integer.parseInt(txtCantidadDetallesVenta.getText().toString().trim()));
           int cantidad=Integer.parseInt(txtCantidadDetallesVenta.getText().toString().trim());
           int  subtotal=precio*cantidad;
           txtSubTotalDetallesVenta.setText(subtotal+""); */


    }//GEN-LAST:event_txtCantidadDetallesVentaKeyPressed

    private void txtSubTotalDetallesVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalDetallesVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalDetallesVentaActionPerformed

    private void txtCantidadDetallesVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadDetallesVentaKeyReleased

        try {
            int precio = Integer.parseInt(txtPrecioDetallesVenta.getText().toString().trim());

            int cantidad = Integer.parseInt(txtCantidadDetallesVenta.getText().toString().trim());
            int subtotal = precio * cantidad;
            txtSubTotalDetallesVenta.setText(subtotal + "");
        } catch (Exception e) {
        }

    }//GEN-LAST:event_txtCantidadDetallesVentaKeyReleased

    private void btncancelarDetallesVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarDetallesVentaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        principalUsuarios.controldetallesVenderProducto = false;
        principal.controldetallesVenderProducto = false;
    }//GEN-LAST:event_btncancelarDetallesVentaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        principal.controldetallesVenderProducto = false;
        principalUsuarios.controldetallesVenderProducto = false;

    }//GEN-LAST:event_formWindowClosing

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
       principal.controldetallesVenderProducto=false;
        dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detallesVenderProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detallesVenderProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detallesVenderProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detallesVenderProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detallesVenderProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarDetallesVenta;
    private javax.swing.JButton btncancelarDetallesVenta;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JLabel labelFotoDetallesVenta;
    private javax.swing.JTextField txtCantidadDetallesVenta;
    public static javax.swing.JTextField txtExistenciasDetallesVenta;
    public static javax.swing.JTextField txtNombreDetallesVenta;
    public static javax.swing.JTextField txtPrecioDetallesVenta;
    private javax.swing.JTextField txtSubTotalDetallesVenta;
    // End of variables declaration//GEN-END:variables
}
