/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import NuevasPantallas.principal;
import beans.Productos;
import control.ImagePreview;
import control.Utils;
import control.controlProductoPendientes;
import control.controlProductos;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import modelo.daoProductos;
import validaciones.validarCampos;
import java.awt.MouseInfo;
import java.awt.Point;
import modelo.daoProductosApartados;

/**
 *
 * @author famsa
 */
public class editarProductoPendientes2019 extends javax.swing.JFrame {

    //para el frame
    int x = 0, y = 0;
    daoProductos dao = new daoProductos();
    Image foto;
    File file;
    public static String idproApa = "";//biene  de productos pendientes
    public static Productos bean = new Productos();
    //ESTOS  VALORES defaultTabla-->SON LLENADOS DESDE LA PANTALLA PRINCIPAL
    public static DefaultTableModel defaultTabla = new DefaultTableModel();
    public static JTable tabla = new JTable();
//=========================== INSTANCIAMOS LA CLASES QUE UTILIZAREMOS ======================================
    validarCampos validar = new validarCampos();

    controlProductos controlPro = new controlProductos();
    controlProductoPendientes controlProA = new controlProductoPendientes();

    /**
     * Creates new form editarProducto
     */
    public editarProductoPendientes2019() {
        initComponents();
        principal.frameeditarProductoPendientes2019 = this;
        this.setTitle("Editar Producto");
        this.setLocationRelativeTo(null);
        //VALIDAMOS LOS CAMPOS
        txtIdEditarProducto.setVisible(false);
        validar.soloNumerosYLetras(txtDescripcionEditarProducto);

        //LLENAMOS LOS CAMPOS CON EL BEAN QUE NOSTRAEMOS DESDE EL CONTORL PRODUCTOS
        llenarCampos();

    }

    public void llenarCampos() {
        daoProductosApartados dao = new daoProductosApartados();
        System.out.println("clavePro " + idproApa);
        Productos bean = dao.consultaParaEditarPro2019(idproApa);
        if (bean != null) {
            txtIdEditarProducto.setText(bean.getIdproductos() + "");
            txtDescripcionEditarProducto.setText(bean.getDescripcion().toUpperCase());
            if (bean.getFoto() == null) {
                labelFotoEditarProducto.setText("Sin foto");
            } else {
                Image imagen;
                try {
                    imagen = dao.getImg(bean.getFoto(), false);// dao.getImage(bean, false);
                    Icon icon = new ImageIcon(imagen.getScaledInstance(127, 190, Image.SCALE_DEFAULT));
                    labelFotoEditarProducto.setIcon(icon);
                } catch (Exception ex) {

                    JOptionPane.showMessageDialog(null, "Error en editarproductoPendientes llenarCampos", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);

                }
            }

        } else {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcionEditarProducto = new javax.swing.JTextArea();
        btnAceptarEditarProducto = new javax.swing.JButton();
        btnCancelarEditarProducto = new javax.swing.JButton();
        btnBuscarFotoEditarProducto = new javax.swing.JButton();
        labelFotoEditarProducto = new javax.swing.JLabel();
        txtIdEditarProducto = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 204));
        jLabel15.setText("Descripción:");

        txtDescripcionEditarProducto.setColumns(20);
        txtDescripcionEditarProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDescripcionEditarProducto.setRows(5);
        txtDescripcionEditarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionEditarProductoKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(txtDescripcionEditarProducto);

        btnAceptarEditarProducto.setBackground(new java.awt.Color(255, 0, 204));
        btnAceptarEditarProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAceptarEditarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptarEditarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editar.png"))); // NOI18N
        btnAceptarEditarProducto.setText("Editar");
        btnAceptarEditarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptarEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarEditarProductoActionPerformed(evt);
            }
        });

        btnCancelarEditarProducto.setBackground(new java.awt.Color(255, 0, 204));
        btnCancelarEditarProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCancelarEditarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarEditarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        btnCancelarEditarProducto.setText("Cancelar");
        btnCancelarEditarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEditarProductoActionPerformed(evt);
            }
        });

        btnBuscarFotoEditarProducto.setBackground(new java.awt.Color(255, 0, 204));
        btnBuscarFotoEditarProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBuscarFotoEditarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarFotoEditarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png"))); // NOI18N
        btnBuscarFotoEditarProducto.setText("Buscar foto");
        btnBuscarFotoEditarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarFotoEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFotoEditarProductoActionPerformed(evt);
            }
        });

        labelFotoEditarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFotoEditarProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtIdEditarProducto.setEditable(false);
        txtIdEditarProducto.setBackground(new java.awt.Color(229, 222, 222));
        txtIdEditarProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 0, 204));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Editar datos del producto");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/minimizar.png"))); // NOI18N
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtIdEditarProducto)
                .addGap(314, 314, 314))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelFotoEditarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarFotoEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnCancelarEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnAceptarEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtIdEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelFotoEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarFotoEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel15)))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        principal.controleditarProductoPendientes2019 = false;
    }//GEN-LAST:event_formWindowClosing

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_formMouseDragged

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        principal.controleditarProductoPendientes2019 = false;
        dispose();
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void btnBuscarFotoEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFotoEditarProductoActionPerformed
        //tutorial   https://codigo--java.blogspot.mx/2014/06/uso-basico-de-elementos-swing-con_5.html
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de archivos JPEG(*.JPG ;*.JEPG;*.PNG)", "jpg", "jpeg", "png");
        JFileChooser archivo = new JFileChooser();
        archivo.addChoosableFileFilter(filtro);
        //=============== pruebass ============
        //Creamos un filtro de imágenes utilizando nuestra clase Utils
        archivo.addChoosableFileFilter(new FileFilter() {
            //Los métos siguientes son implementaciones
            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                }
                String exts = Utils.getExtension(f);
                if (exts != null) {
                    if (exts.equals(Utils.tiff)
                            || exts.equals(Utils.tif)
                            || exts.equals(Utils.gif)
                            || exts.equals(Utils.jpeg)
                            || exts.equals(Utils.jpg)
                            || exts.equals(Utils.png)) {
                        return true;
                    } else {
                        return false;
                    }
                }

                return false;

            }

            @Override
            public String getDescription() {
                return "Imágenes";
            }
        });
        //Establecemos un accesorio que será nuestra vista previa.
        archivo.setAccessory(new ImagePreview(archivo));
        //showOpenDialog para JFileChooser de apertura.
        //Guardamos el valor en un entero, pues es lo que retorna.
        //        int rs = archivo.showOpenDialog(this);
        //Comprabamos el retorno como vemos más abajo.

        //================ hasta aqui=============
        archivo.setDialogTitle("Abrir archivo");

        int ventana = archivo.showOpenDialog(null);

        if (ventana == JFileChooser.APPROVE_OPTION) {
            file = archivo.getSelectedFile();

            foto = getToolkit().getImage(String.valueOf(file));
            // getImage(String.valueOf(file));
            foto = foto.getScaledInstance(127, 190, Image.SCALE_DEFAULT);
            labelFotoEditarProducto.setIcon(new ImageIcon(foto));

        }
    }//GEN-LAST:event_btnBuscarFotoEditarProductoActionPerformed

    private void btnCancelarEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEditarProductoActionPerformed
        dispose();
        principal.controleditarProducto = false;
    }//GEN-LAST:event_btnCancelarEditarProductoActionPerformed

    private void btnAceptarEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarEditarProductoActionPerformed
        // String tipo = spinnerEditarProducto.getSelectedItem().toString();
       controlProA.editarProductos2019(txtIdEditarProducto,
                txtDescripcionEditarProducto, labelFotoEditarProducto, file, this, idproApa);
//controlPro.editar(txtIdEditarProducto, txtClaveEditarProducto, txtNombreEditarProducto, txtPrecioEditarProducto, txtColorEditarProducto, tipo, txtCantidadEditarProducto, txtDescripcionEditarProducto, labelFotoEditarProducto, file, this, tabla, defaultTabla);
    }//GEN-LAST:event_btnAceptarEditarProductoActionPerformed

    private void txtDescripcionEditarProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionEditarProductoKeyTyped
        //if (txtPrecioEditarProducto.getText().length() == 99) {
        //  evt.consume();

        //}
    }//GEN-LAST:event_txtDescripcionEditarProductoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editarProductoPendientes2019.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editarProductoPendientes2019.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editarProductoPendientes2019.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editarProductoPendientes2019.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editarProductoPendientes2019().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarEditarProducto;
    private javax.swing.JButton btnBuscarFotoEditarProducto;
    private javax.swing.JButton btnCancelarEditarProducto;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelFotoEditarProducto;
    private javax.swing.JTextArea txtDescripcionEditarProducto;
    private javax.swing.JTextField txtIdEditarProducto;
    // End of variables declaration//GEN-END:variables
}
