/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import beans.Productos;
import control.ImagePreview;
import control.Utils;
import control.controlProductos;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import modelo.daoProductos;
import validaciones.validarCampos;

/**
 *
 * @author famsa
 */
public class editarProducto3 extends javax.swing.JFrame {
    daoProductos dao = new daoProductos();
    Image foto;
    File file;
    public static Productos bean =new Productos();
    //ESTOS  VALORES defaultTabla-->SON LLENADOS DESDE LA PANTALLA PRINCIPAL
    public static DefaultTableModel defaultTabla= new DefaultTableModel();
    public static JTable tabla = new JTable();
//=========================== INSTANCIAMOS LA CLASES QUE UTILIZAREMOS ======================================
     validarCampos validar = new validarCampos();
    
     controlProductos controlPro= new controlProductos();
    /**
     * Creates new form editarProducto
     */
    public editarProducto3() {
        initComponents();
        principal1.frameeditarProducto=this;
        this.setTitle("Editar Producto");
        this.setLocationRelativeTo(null);
        //VALIDAMOS LOS CAMPOS
        validar.soloNumeros(txtClaveEditarProducto);
        validar.soloLetras(txtNombreEditarProducto);
        validar.soloNumeros(txtPrecioEditarProducto);
        validar.soloLetras(txtColorEditarProducto);
        validar.soloNumeros(txtCantidadEditarProducto);
        validar.soloNumerosYLetras(txtDescripcionEditarProducto);
        
        //LLENAMOS LOS CAMPOS CON EL BEAN QUE NOSTRAEMOS DESDE EL CONTORL PRODUCTOS
        
        System.out.println("id " + bean.getIdproductos()+"");
        txtIdEditarProducto.setText(bean.getIdproductos()+"");
        txtClaveEditarProducto.setText(bean.getClave()+"");
        txtNombreEditarProducto.setText(bean.getNombre());
        txtPrecioEditarProducto.setText(bean.getPrecio()+"");
        txtColorEditarProducto.setText(bean.getColor());
        txtCantidadEditarProducto.setText(bean.getCantidad()+"");
        txtDescripcionEditarProducto.setText(bean.getDescripcion());
        spinnerEditarProducto.setSelectedItem(bean.getTipo());
        System.out.println("fotoot " + bean.getFoto());
      
        if (bean.getFoto()==null) {
            labelFotoEditarProducto.setText("Sin foto");
        }else{
            Image imagen;
            try {
                imagen = dao.getImage(bean, false);
                Icon icon = new ImageIcon(imagen.getScaledInstance(127, 190, Image.SCALE_DEFAULT));
                labelFotoEditarProducto.setIcon(icon);
            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, "Error el metodo jButton4ActionPerformed de la pantalla PRINCIPAL", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);

            }
        }
          JOptionPane.showMessageDialog(null, "EL  prodcuto ya esta registrado " + "\n pero no tienes permiso para editar ningun dato"+"\nConsulta al administrador", "MENSAJE DE ERROR", JOptionPane.WARNING_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtClaveEditarProducto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNombreEditarProducto = new javax.swing.JTextField();
        txtPrecioEditarProducto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtColorEditarProducto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCantidadEditarProducto = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        spinnerEditarProducto = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcionEditarProducto = new javax.swing.JTextArea();
        btnAceptarEditarProducto = new javax.swing.JButton();
        btnCancelarEditarProducto = new javax.swing.JButton();
        btnBuscarFotoEditarProducto = new javax.swing.JButton();
        labelFotoEditarProducto = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtIdEditarProducto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Producto", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 18))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Clave:");

        txtClaveEditarProducto.setEditable(false);
        txtClaveEditarProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtClaveEditarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveEditarProductoKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Nombre:");

        txtNombreEditarProducto.setEditable(false);
        txtNombreEditarProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNombreEditarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreEditarProductoKeyTyped(evt);
            }
        });

        txtPrecioEditarProducto.setEditable(false);
        txtPrecioEditarProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPrecioEditarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioEditarProductoKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Precio:");

        txtColorEditarProducto.setEditable(false);
        txtColorEditarProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtColorEditarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColorEditarProductoKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Color:");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Cantidad:");

        txtCantidadEditarProducto.setEditable(false);
        txtCantidadEditarProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCantidadEditarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadEditarProductoKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Descripción:");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Tipo:");

        txtDescripcionEditarProducto.setEditable(false);
        txtDescripcionEditarProducto.setColumns(20);
        txtDescripcionEditarProducto.setRows(5);
        txtDescripcionEditarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionEditarProductoKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(txtDescripcionEditarProducto);

        btnAceptarEditarProducto.setText("Editar");
        btnAceptarEditarProducto.setEnabled(false);
        btnAceptarEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarEditarProductoActionPerformed(evt);
            }
        });

        btnCancelarEditarProducto.setText("Cancelar");
        btnCancelarEditarProducto.setEnabled(false);
        btnCancelarEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEditarProductoActionPerformed(evt);
            }
        });

        btnBuscarFotoEditarProducto.setText("Buscar foto");
        btnBuscarFotoEditarProducto.setEnabled(false);
        btnBuscarFotoEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFotoEditarProductoActionPerformed(evt);
            }
        });

        labelFotoEditarProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Id:");

        txtIdEditarProducto.setEditable(false);
        txtIdEditarProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(btnAceptarEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnCancelarEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCantidadEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtClaveEditarProducto)
                                    .addComponent(txtNombreEditarProducto)
                                    .addComponent(txtPrecioEditarProducto)
                                    .addComponent(txtColorEditarProducto)
                                    .addComponent(spinnerEditarProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel17)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(txtIdEditarProducto)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscarFotoEditarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(labelFotoEditarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(175, 175, 175))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(labelFotoEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarFotoEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addContainerGap(48, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtIdEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtClaveEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtPrecioEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtColorEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(spinnerEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtCantidadEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel15))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarEditarProductoActionPerformed
        String tipo= spinnerEditarProducto.getSelectedItem().toString();
        controlPro.editar(txtIdEditarProducto, txtClaveEditarProducto, txtNombreEditarProducto, txtPrecioEditarProducto, txtColorEditarProducto, tipo, txtCantidadEditarProducto, txtDescripcionEditarProducto, labelFotoEditarProducto, file,this,tabla,defaultTabla);
    }//GEN-LAST:event_btnAceptarEditarProductoActionPerformed

    private void btnCancelarEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEditarProductoActionPerformed
    dispose();
    principal1.controleditarProducto=false;
    }//GEN-LAST:event_btnCancelarEditarProductoActionPerformed

    private void btnBuscarFotoEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFotoEditarProductoActionPerformed
        //tutorial   https://codigo--java.blogspot.mx/2014/06/uso-basico-de-elementos-swing-con_5.html
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de archivos JPEG(*.JPG ;*.JEPG;*.PNG)", "jpg", "jpeg", "png");
        JFileChooser archivo = new JFileChooser();
        archivo.addChoosableFileFilter(filtro);
        //=============== pruebass ============
        //Creamos un filtro de imágenes utilizando nuestra clase Utils
        archivo.addChoosableFileFilter(new FileFilter() {
            //Los métos siguientes son implementaciones
            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                }
                String exts = Utils.getExtension(f);
                if (exts != null) {
                    if (exts.equals(Utils.tiff)
                        || exts.equals(Utils.tif)
                        || exts.equals(Utils.gif)
                        || exts.equals(Utils.jpeg)
                        || exts.equals(Utils.jpg)
                        || exts.equals(Utils.png)) {
                        return true;
                    } else {
                        return false;
                    }
                }

                return false;

            }

            @Override
            public String getDescription() {
                return "Imágenes";
            }
        });
        //Establecemos un accesorio que será nuestra vista previa.
        archivo.setAccessory(new ImagePreview(archivo));
        //showOpenDialog para JFileChooser de apertura.
        //Guardamos el valor en un entero, pues es lo que retorna.
        //        int rs = archivo.showOpenDialog(this);
        //Comprabamos el retorno como vemos más abajo.

        //================ hasta aqui=============
        archivo.setDialogTitle("Abrir archivo");

        int ventana = archivo.showOpenDialog(null);

        if (ventana == JFileChooser.APPROVE_OPTION) {
            file = archivo.getSelectedFile();

            foto = getToolkit().getImage(String.valueOf(file));
            // getImage(String.valueOf(file));
            foto = foto.getScaledInstance(127, 190, Image.SCALE_DEFAULT);
            labelFotoEditarProducto.setIcon(new ImageIcon(foto));

        }
    }//GEN-LAST:event_btnBuscarFotoEditarProductoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        principal1.controleditarProducto=false;
    }//GEN-LAST:event_formWindowClosing

    private void txtClaveEditarProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveEditarProductoKeyTyped
         if(txtClaveEditarProducto.getText().length()== 39)
        {
            evt.consume();

        }
    }//GEN-LAST:event_txtClaveEditarProductoKeyTyped

    private void txtNombreEditarProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEditarProductoKeyTyped
         if(txtNombreEditarProducto.getText().length()== 19)
        {
            evt.consume();

        }
    }//GEN-LAST:event_txtNombreEditarProductoKeyTyped

    private void txtPrecioEditarProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioEditarProductoKeyTyped
 if(txtPrecioEditarProducto.getText().length()== 10)
        {
            evt.consume();

        }       
    }//GEN-LAST:event_txtPrecioEditarProductoKeyTyped

    private void txtColorEditarProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorEditarProductoKeyTyped
        if(txtColorEditarProducto.getText().length()== 19)
        {
            evt.consume();

        }   
    }//GEN-LAST:event_txtColorEditarProductoKeyTyped

    private void txtCantidadEditarProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadEditarProductoKeyTyped
        if(txtCantidadEditarProducto.getText().length()== 10)
        {
            evt.consume();

        }   
    }//GEN-LAST:event_txtCantidadEditarProductoKeyTyped

    private void txtDescripcionEditarProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionEditarProductoKeyTyped
       if(txtPrecioEditarProducto.getText().length()== 99)
        {
            evt.consume();

        }   
    }//GEN-LAST:event_txtDescripcionEditarProductoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editarProducto3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editarProducto3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editarProducto3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editarProducto3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editarProducto3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarEditarProducto;
    private javax.swing.JButton btnBuscarFotoEditarProducto;
    private javax.swing.JButton btnCancelarEditarProducto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelFotoEditarProducto;
    private javax.swing.JComboBox<String> spinnerEditarProducto;
    private javax.swing.JTextField txtCantidadEditarProducto;
    private javax.swing.JTextField txtClaveEditarProducto;
    private javax.swing.JTextField txtColorEditarProducto;
    private javax.swing.JTextArea txtDescripcionEditarProducto;
    private javax.swing.JTextField txtIdEditarProducto;
    private javax.swing.JTextField txtNombreEditarProducto;
    private javax.swing.JTextField txtPrecioEditarProducto;
    // End of variables declaration//GEN-END:variables
}
