/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//chales
package NuevasPantallas;

import ModeloProductos.DaoProductos;
import ModeloProductos.DetallesProductos;
import ModeloProductos.productos;
import control.controlProductos;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import pantallas.DetallesProducto;


/**
 *
 * @author famsa
 */
public class catalogo extends javax.swing.JFrame {
    //para el frame
    int x = 0, y = 0;
//=============================  PARA  EL CATALOGO  PRODUCTOS =========================================
    int canlis;
    int contCatalogoImg = 0;
    /**
     * Creates new form catalogo
     */
    //los daos
    DaoProductos daoProductosCatalogo = new DaoProductos();
     controlProductos controlPro = new controlProductos();
    public catalogo() {
        initComponents();
        this.setState(MAXIMIZED_BOTH);
        principal.framecatalogo=this;
        
        //================================  PARA EL CATALGO PRODUCTOS =============================
//Todo esto usamos para el catalogo
        btnAtras.setEnabled(false);
        //this.setExtendedState(MAXIMIZED_BOTH);
        labelImg11.setIcon(null);
        //para el catalogo por default vamos a dejar 8 fotos de manera estatica se podria decir
        //cuando se presion el boton siguiente el contador ira a avanzado y cambiara las 8 imagenes y pondra otras 8 nueva
        //validaremos si aun la lista de imagenes aun tiene y si ya no tiene los cuadros que quedan vacios les pondremos una foto estatica

        //este contador nos va servir para ir moviendo el boton next y atras conforme avanse
        //declaramos nuesta calse dao
        //creamos una lista para recibir los valoles del dao aqui recibimos byte[]
        //aqui mero mero maromero
        new controlProductos().llenarListaImg(labelImg11, labelImg12, labelImg13, labelImg14, labelImg15, labelImg16, labelImg17, labelImg29,
                btnAtras, btnSiguiente, labelIdProducto16, labelIdProducto17, labelIdProducto18, labelIdProducto19, labelIdProducto20,
                labelIdProducto21, labelIdProducto22, labelIdProducto23, contCatalogoImg, canlis);
//OCULTAMOS LOS LABEL DONDE PONEMOS LOS ID DE PRODUCTOS
        labelIdProducto16.setVisible(false);
        labelIdProducto17.setVisible(false);
        labelIdProducto18.setVisible(false);
        labelIdProducto19.setVisible(false);
        labelIdProducto20.setVisible(false);
        labelIdProducto21.setVisible(false);
        labelIdProducto22.setVisible(false);
        labelIdProducto23.setVisible(false);

//============================================== HERE TERMINA ==============================================================================================
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboxTipo = new javax.swing.JComboBox();
        labelBuscar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnActualizarCatalogo = new javax.swing.JButton();
        labelImg11 = new javax.swing.JLabel();
        labelImg12 = new javax.swing.JLabel();
        labelImg13 = new javax.swing.JLabel();
        labelImg14 = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        labelImg29 = new javax.swing.JLabel();
        labelImg17 = new javax.swing.JLabel();
        labelImg16 = new javax.swing.JLabel();
        labelImg15 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        labelIdProducto16 = new javax.swing.JLabel();
        labelIdProducto17 = new javax.swing.JLabel();
        labelIdProducto18 = new javax.swing.JLabel();
        labelIdProducto19 = new javax.swing.JLabel();
        labelIdProducto20 = new javax.swing.JLabel();
        labelIdProducto21 = new javax.swing.JLabel();
        labelIdProducto22 = new javax.swing.JLabel();
        labelIdProducto23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));

        comboxTipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        comboxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Novia", "IV años", "Presentacion", "Trajes" }));

        labelBuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelBuscar.setForeground(new java.awt.Color(255, 0, 204));
        labelBuscar.setText("Buscar Por:");

        btnBuscar.setBackground(new java.awt.Color(255, 51, 255));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnActualizarCatalogo.setBackground(new java.awt.Color(255, 51, 255));
        btnActualizarCatalogo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnActualizarCatalogo.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarCatalogo.setText("Actulizar  Catalogo");
        btnActualizarCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCatalogoActionPerformed(evt);
            }
        });

        labelImg11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelImg11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelImg11MousePressed(evt);
            }
        });

        labelImg12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelImg12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelImg12MousePressed(evt);
            }
        });

        labelImg13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelImg13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelImg13MousePressed(evt);
            }
        });

        labelImg14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelImg14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelImg14MousePressed(evt);
            }
        });

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nextt.png"))); // NOI18N
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        labelImg29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelImg29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelImg29MousePressed(evt);
            }
        });

        labelImg17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelImg17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelImg17MousePressed(evt);
            }
        });

        labelImg16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelImg16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelImg16MousePressed(evt);
            }
        });

        labelImg15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelImg15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelImg15MousePressed(evt);
            }
        });

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/atras.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        labelIdProducto16.setText("jLabel16");

        labelIdProducto17.setText("jLabel17");

        labelIdProducto18.setText("jLabel18");

        labelIdProducto19.setText("jLabel19");

        labelIdProducto20.setText("jLabel20");

        labelIdProducto21.setText("jLabel21");

        labelIdProducto22.setText("jLabel22");

        labelIdProducto23.setText("jLabel23");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(517, 517, 517))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdProducto16)
                    .addComponent(labelIdProducto17)
                    .addComponent(labelIdProducto18)
                    .addComponent(labelIdProducto19)
                    .addComponent(labelIdProducto20)
                    .addComponent(labelIdProducto21)
                    .addComponent(labelIdProducto22)
                    .addComponent(labelIdProducto23))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImg11, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelImg15, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImg16, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelImg12, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImg13, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelImg17, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelImg14, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelImg29, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarCatalogo)
                    .addComponent(btnBuscar)
                    .addComponent(comboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelImg13, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelImg17, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(labelImg12, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelImg16, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelImg11, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelIdProducto16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelIdProducto17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelIdProducto18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelIdProducto19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelIdProducto20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelIdProducto21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelIdProducto22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelIdProducto23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                                .addComponent(btnAtras)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelImg15, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelImg14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSiguiente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelImg29, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String tipo = comboxTipo.getSelectedItem().toString();
        String estado = "";

        //            System.out.println("entro al check vestiso seleccionado");
        estado = "Vendido";
        //Mandamos a traer un metodo donde el status sea vendido mas el tipo de opcion bod,IV años etc
        //creamos una lista para recibir los valoles del dao aqui recibimos byte[]
        contCatalogoImg = 0;
        List<productos> listaProCatalgo = daoProductosCatalogo.consultarImageParaCatalogoTipoyEstado(tipo, estado);
        if (listaProCatalgo.size() != 0) {
            List<DetallesProductos> listaImg = new ArrayList<>();
            Image imagen = null;
            for (int i = 0; i < listaProCatalgo.size(); i++) {
                DetallesProductos beanDetallesPro = new DetallesProductos();
                try {
                    imagen = daoProductosCatalogo.getImage(listaProCatalgo.get(i), false);
                    beanDetallesPro.setImagen(imagen);
                    beanDetallesPro.setIdProducto(listaProCatalgo.get(i).getIdProductos());
                    listaImg.add(beanDetallesPro);
                } catch (Exception ex) {
                    System.out.println("error en la imagenes");
                }
            }
            if (listaImg.size() < 9) {
                btnSiguiente.setEnabled(false);
            }
            //here mero llenarCatalago(listaImg);
        } else {
            JOptionPane.showMessageDialog(null, "No hay productos", "MENSAJE DE ALERTA", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCatalogoActionPerformed
        controlPro.llenarListaImg(labelImg11, labelImg12, labelImg13, labelImg14, labelImg15, labelImg16, labelImg17, labelImg29, btnAtras, btnSiguiente, labelIdProducto16, labelIdProducto17, labelIdProducto18, labelIdProducto19, labelIdProducto20, labelIdProducto21, labelIdProducto22, labelIdProducto23, contCatalogoImg, canlis);
    }//GEN-LAST:event_btnActualizarCatalogoActionPerformed
//====================================  PARA EL CATALOGO DE PRODUCTOS  ==================================
    public void consultarDetallesProducto(int idProducto) {
        DetallesProducto beanDetallesPro = new DetallesProducto();
        productos bean = daoProductosCatalogo.consultarImage(idProducto);
        Image imagen;
//        List<Image> listaImg = new ArrayList<Image>();
        try {
            if (principal.controlDetallesProducto == false) {

                imagen = daoProductosCatalogo.getImage(bean, false);
//            listaImg.add(imagen);
//            Icon i=new ImageIcon(listaImg.get(1).getScaledInstance(2, 3, listaImg.get(1).SCALE_DEFAULT));
                //este icon se supone que ya es la imagen literalmente entonces aremos un arrayList<Image>
                Icon icon = new ImageIcon(imagen.getScaledInstance(360, 670, Image.SCALE_DEFAULT));
                DetallesProducto.labelFoto.setIcon(icon);
                DetallesProducto.txtCodigo.setText(bean.getClave());
                DetallesProducto.txtPrecio.setText(String.valueOf(bean.getPrecio()));

                beanDetallesPro.setVisible(true);
                principal.controlDetallesProducto = true;
            } else {
                JOptionPane.showMessageDialog(null, "Ya esta abierto esta ventana", "MENSAJE DE ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                principal.frameDetallesProducto.setAlwaysOnTop(true);
            }
        } catch (Exception ex) {
            System.out.println("error al cargar al imagen " + ex);
        }
    }
//==================================== HERE AQUIIIIIIIIIIIIIIIIIIIIII ===================================    

    private void labelImg11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImg11MousePressed
        // TODO add your handling code here:
        if (labelIdProducto16.getText().toString().equals("")) {

        } else {
            consultarDetallesProducto(Integer.parseInt(labelIdProducto16.getText().toString()));
        }
    }//GEN-LAST:event_labelImg11MousePressed

    private void labelImg12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImg12MousePressed
        // TODO add your handling code here:
        if (labelIdProducto17.getText().toString().equals("")) {

        } else {
            consultarDetallesProducto(Integer.parseInt(labelIdProducto17.getText().toString()));
        }
    }//GEN-LAST:event_labelImg12MousePressed

    private void labelImg13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImg13MousePressed
        // TODO add your handling code here:
        if (labelIdProducto18.getText().toString().equals("")) {

        } else {
            consultarDetallesProducto(Integer.parseInt(labelIdProducto18.getText().toString()));
        }
    }//GEN-LAST:event_labelImg13MousePressed

    private void labelImg14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImg14MousePressed
        // TODO add your handling code here:
        if (labelIdProducto19.getText().toString().equals("")) {

        } else {
            consultarDetallesProducto(Integer.parseInt(labelIdProducto19.getText().toString()));
        }
    }//GEN-LAST:event_labelImg14MousePressed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        contCatalogoImg++;

        //este contador nos va servir para ir moviendo el boton next y atras conforme avanse
        //declaramos nuesta calse dao
        //creamos una lista para recibir los valoles del dao aqui recibimos byte[]
        List<productos> listaProCatalgo = daoProductosCatalogo.consultarImageParaCatalogo();

        List<DetallesProductos> listaImg = new ArrayList<>();
        Image imagen = null;
        for (int i = 0; i < listaProCatalgo.size(); i++) {
            DetallesProductos beanDetallesPro = new DetallesProductos();
            try {
                imagen = daoProductosCatalogo.getImage(listaProCatalgo.get(i), false);
                beanDetallesPro.setImagen(imagen);
                beanDetallesPro.setIdProducto(listaProCatalgo.get(i).getIdProductos());
                listaImg.add(beanDetallesPro);
            } catch (IOException ex) {
                System.out.println("error en la imagenes");
            }
        }
        //        System.out.println("en boton Siguiente" + listaImg.size());
        if (listaImg.size() < 9) {
            btnSiguiente.setEnabled(false);
        }

        //here mero llenarCatalago(listaImg);
        //        System.out.println("cont btn " + contCatalogoImg);
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void labelImg29MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImg29MousePressed
        // TODO add your handling code here:
        if (labelIdProducto23.getText().toString().equals("")) {

        } else {
            consultarDetallesProducto(Integer.parseInt(labelIdProducto23.getText().toString()));
        }
    }//GEN-LAST:event_labelImg29MousePressed

    private void labelImg17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImg17MousePressed
        // TODO add your handling code here:
        if (labelIdProducto22.getText().toString().equals("")) {

        } else {
            consultarDetallesProducto(Integer.parseInt(labelIdProducto22.getText().toString()));
        }
    }//GEN-LAST:event_labelImg17MousePressed

    private void labelImg16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImg16MousePressed
        // TODO add your handling code here:
        if (labelIdProducto21.getText().toString().equals("")) {

        } else {
            consultarDetallesProducto(Integer.parseInt(labelIdProducto21.getText().toString()));
        }
    }//GEN-LAST:event_labelImg16MousePressed

    private void labelImg15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImg15MousePressed
        // TODO add your handling code here:
        if (labelIdProducto20.getText().toString().equals("")) {

        } else {
            consultarDetallesProducto(Integer.parseInt(labelIdProducto20.getText().toString()));
        }
    }//GEN-LAST:event_labelImg15MousePressed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        if (contCatalogoImg <= 15) {
            //            System.out.println("entro en es igual a 15");
            contCatalogoImg = 0;
        } else {
            contCatalogoImg = contCatalogoImg - 15;
            //            System.out.println("entro en no es igual a 15");
        }
        //este contador nos va servir para ir moviendo el boton next y atras conforme avanse
        //declaramos nuesta calse dao

        //creamos una lista para recibir los valoles del dao aqui recibimos byte[]
        List<productos> listaProCatalgo = daoProductosCatalogo.consultarImageParaCatalogo();
        if (listaProCatalgo.size() != 0) {
            List<DetallesProductos> listaImg = new ArrayList<>();
            Image imagen = null;
            for (int i = 0; i < listaProCatalgo.size(); i++) {
                DetallesProductos beanDetallesPro = new DetallesProductos();
                try {
                    imagen = daoProductosCatalogo.getImage(listaProCatalgo.get(i), false);
                    beanDetallesPro.setImagen(imagen);
                    beanDetallesPro.setIdProducto(listaProCatalgo.get(i).getIdProductos());
                    listaImg.add(beanDetallesPro);
                } catch (IOException ex) {
                    System.out.println("error en la imagenes");
                }
            }
            //            System.out.println("en boton Siguiente" + listaImg.size());
            if (listaImg.size() < 9) {
                btnSiguiente.setEnabled(false);
            }

            //here mero llenarCatalago(listaImg);
            //            System.out.println("cont btn " + contCatalogoImg);
        } else {
            JOptionPane.showMessageDialog(null, "No hay productos", "MENSAJE DE ALERTA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new catalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCatalogo;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox comboxTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JLabel labelIdProducto16;
    private javax.swing.JLabel labelIdProducto17;
    private javax.swing.JLabel labelIdProducto18;
    private javax.swing.JLabel labelIdProducto19;
    private javax.swing.JLabel labelIdProducto20;
    private javax.swing.JLabel labelIdProducto21;
    private javax.swing.JLabel labelIdProducto22;
    private javax.swing.JLabel labelIdProducto23;
    private javax.swing.JLabel labelImg11;
    private javax.swing.JLabel labelImg12;
    private javax.swing.JLabel labelImg13;
    private javax.swing.JLabel labelImg14;
    private javax.swing.JLabel labelImg15;
    private javax.swing.JLabel labelImg16;
    private javax.swing.JLabel labelImg17;
    private javax.swing.JLabel labelImg29;
    // End of variables declaration//GEN-END:variables
}
