package beans;
// Generated 08-jun-2018 21:10:54 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Fechaspruebas generated by hbm2java
 */
public class Fechaspruebas implements java.io.Serializable {

    private int idProducto;
    private Integer idfechaspruebas;
    private Productosapartados productosapartados;
    private String fechaprueba;
    private String fechaevento;
    private Date fechaprueba2;
    private Date fechaevento2;
    private String fecharegistro;

    public Fechaspruebas() {
    }

    public Fechaspruebas(String fechaevento) {
        this.fechaevento = fechaevento;
    }

    public Fechaspruebas(Productosapartados productosapartados, String fechaprueba, String fechaevento, String fecharegistro) {
        this.productosapartados = productosapartados;
        this.fechaprueba = fechaprueba;
        this.fechaevento = fechaevento;
        this.fecharegistro = fecharegistro;
    }

    public int getIdProducto() {
        return idProducto;
    }

    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }

    public Integer getIdfechaspruebas() {
        return this.idfechaspruebas;
    }

    public void setIdfechaspruebas(Integer idfechaspruebas) {
        this.idfechaspruebas = idfechaspruebas;
    }

    public Productosapartados getProductosapartados() {
        return this.productosapartados;
    }

    public void setProductosapartados(Productosapartados productosapartados) {
        this.productosapartados = productosapartados;
    }

    public String getFechaprueba() {
        return this.fechaprueba;
    }

    public void setFechaprueba(String fechaprueba) {
        this.fechaprueba = fechaprueba;
    }

    public String getFechaevento() {
        return this.fechaevento;
    }

    public void setFechaevento(String fechaevento) {
        this.fechaevento = fechaevento;
    }

    public String getFecharegistro() {
        return this.fecharegistro;
    }

    public void setFecharegistro(String fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    public Date getFechaprueba2() {
        return fechaprueba2;
    }

    public void setFechaprueba2(Date fechaprueba2) {
        this.fechaprueba2 = fechaprueba2;
    }

    public Date getFechaevento2() {
        return fechaevento2;
    }

    public void setFechaevento2(Date fechaevento2) {
        this.fechaevento2 = fechaevento2;
    }

}
