package beans;
// Generated 08-jun-2018 21:10:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idproductos;
     private Usuarios usuarios;
     private String clave;
     private Integer precio;
     private String color;
     private String tipo;
     private Date fecharegistro;
     private byte[] foto;
     private String descripcion;
     private Integer cantidad;
     private String nombre;
     private String fotoString;
     private Set productosapartadoses = new HashSet(0);

    public Productos() {
    }

	
    public Productos(String nombre) {
        this.nombre = nombre;
    }
    public Productos(Usuarios usuarios, String clave, Integer precio, String color, String tipo, Date fecharegistro, byte[] foto, String descripcion, Integer cantidad, String nombre, Set productosapartadoses) {
       this.usuarios = usuarios;
       this.clave = clave;
       this.precio = precio;
       this.color = color;
       this.tipo = tipo;
       this.fecharegistro = fecharegistro;
       this.foto = foto;
       this.descripcion = descripcion;
       this.cantidad = cantidad;
       this.nombre = nombre;
       this.productosapartadoses = productosapartadoses;
    }

    public String getFotoString() {
        return fotoString;
    }

    public void setFotoString(String fotoString) {
        this.fotoString = fotoString;
    }
   
    
    public Integer getIdproductos() {
        return this.idproductos;
    }
    
    public void setIdproductos(Integer idproductos) {
        this.idproductos = idproductos;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getProductosapartadoses() {
        return this.productosapartadoses;
    }
    
    public void setProductosapartadoses(Set productosapartadoses) {
        this.productosapartadoses = productosapartadoses;
    }




}


