package beans;
// Generated 08-jun-2018 21:10:54 by Hibernate Tools 4.3.1



/**
 * Productosvendidos generated by hbm2java
 */
public class Productosvendidos  implements java.io.Serializable {


     private Integer idproductosvendidos;
     private Productosapartados productosapartados;
     private String fecharegistro;

    public Productosvendidos() {
    }

	
    public Productosvendidos(String fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public Productosvendidos(Productosapartados productosapartados, String fecharegistro) {
       this.productosapartados = productosapartados;
       this.fecharegistro = fecharegistro;
    }
   
    public Integer getIdproductosvendidos() {
        return this.idproductosvendidos;
    }
    
    public void setIdproductosvendidos(Integer idproductosvendidos) {
        this.idproductosvendidos = idproductosvendidos;
    }
    public Productosapartados getProductosapartados() {
        return this.productosapartados;
    }
    
    public void setProductosapartados(Productosapartados productosapartados) {
        this.productosapartados = productosapartados;
    }
    public String getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(String fecharegistro) {
        this.fecharegistro = fecharegistro;
    }




}


