package beans;
// Generated 08-jun-2018 21:10:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idusuarios;
     private String nombre;
     private String apaterno;
     private String amaterno;
     private String usuario;
     private String contra;
     private Set pagoses = new HashSet(0);
     private Set productoses = new HashSet(0);
     private Set productosapartadoses = new HashSet(0);
     private Set clienteses = new HashSet(0);

    public Usuarios() {
    }

    public Usuarios(String nombre, String apaterno, String amaterno, String usuario, String contra, Set pagoses, Set productoses, Set productosapartadoses, Set clienteses) {
       this.nombre = nombre;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.usuario = usuario;
       this.contra = contra;
       this.pagoses = pagoses;
       this.productoses = productoses;
       this.productosapartadoses = productosapartadoses;
       this.clienteses = clienteses;
    }
   
    public Integer getIdusuarios() {
        return this.idusuarios;
    }
    
    public void setIdusuarios(Integer idusuarios) {
        this.idusuarios = idusuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContra() {
        return this.contra;
    }
    
    public void setContra(String contra) {
        this.contra = contra;
    }
    public Set getPagoses() {
        return this.pagoses;
    }
    
    public void setPagoses(Set pagoses) {
        this.pagoses = pagoses;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }
    public Set getProductosapartadoses() {
        return this.productosapartadoses;
    }
    
    public void setProductosapartadoses(Set productosapartadoses) {
        this.productosapartadoses = productosapartadoses;
    }
    public Set getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set clienteses) {
        this.clienteses = clienteses;
    }




}


